import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — Bluto",
  description: "Terms and conditions for using the Bluto AI companion app.",
};

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <nav className="border-b border-card-border">
        <div className="max-w-3xl mx-auto px-6 h-16 flex items-center">
          <Link href="/" className="flex items-center gap-2">
            <img src="/images/logo-icon.png" alt="Bluto" className="w-7 h-7" />
            <img src="/images/logo-text-name.png" alt="Bluto" className="h-4 w-auto" />
          </Link>
        </div>
      </nav>

      <article className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-2">Terms of Service</h1>
        <p className="text-sm text-muted mb-12">Last updated: April 28, 2026</p>

        <div className="prose-custom space-y-8">
          <p className="text-muted leading-relaxed">
            Welcome to Bluto. By using our app, you agree to the following terms. Please read them carefully.
          </p>

          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted leading-relaxed">
              By accessing or using Bluto, you agree to be bound by these Terms of Service and our{" "}
              <Link href="/privacy" className="text-accent hover:text-accent-light transition-colors">Privacy Policy</Link>.
              If you do not agree to these terms, please do not use the app.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Service Description</h2>
            <p className="text-muted leading-relaxed">
              Bluto is an AI-powered companion app designed for entertainment, productivity, and personal growth. The app provides conversational AI features across various domains including casual chat, fitness, nutrition, astrology, and motivation.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. AI Disclaimer</h2>
            <div className="rounded-xl border border-yellow-500/20 bg-yellow-500/5 p-5 mb-3">
              <p className="text-muted leading-relaxed">
                <strong className="text-foreground">All responses provided by Bluto are generated by artificial intelligence.</strong> You acknowledge and agree that:
              </p>
            </div>
            <ul className="list-disc list-inside space-y-2 text-muted">
              <li>AI responses are for informational and entertainment purposes only and should not be considered professional advice.</li>
              <li>Bluto is <strong className="text-foreground">not</strong> a substitute for professional medical, nutritional, mental health, therapeutic, financial, or legal advice.</li>
              <li>You should always consult qualified professionals for medical, dietary, mental health, or other specialized guidance.</li>
              <li>AI-generated content may occasionally contain inaccuracies. You are responsible for verifying any information before acting on it.</li>
              <li>Astrology-related features are provided for entertainment purposes only.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. User Responsibilities</h2>
            <p className="text-muted leading-relaxed mb-3">When using Bluto, you agree to:</p>
            <ul className="list-disc list-inside space-y-2 text-muted">
              <li>Be at least 13 years of age.</li>
              <li>Provide accurate information when creating your account.</li>
              <li>Not use the app for any unlawful or harmful purpose.</li>
              <li>Not attempt to reverse engineer, exploit, or compromise the app&apos;s systems.</li>
              <li>Not use the app to generate harmful, abusive, or misleading content.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Credits &amp; Payments</h2>
            <p className="text-muted leading-relaxed">
              Bluto uses a credit-based system. New users receive a set of free credits upon signup. Additional credits can be purchased through the app. All purchases are final. Credits have no cash value and cannot be transferred or refunded except as required by applicable law.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Intellectual Property</h2>
            <p className="text-muted leading-relaxed">
              The Bluto app, including its design, features, and content (excluding user-generated content), is owned by Bluto and protected by intellectual property laws. You retain ownership of your own content but grant us a license to process it as needed to provide the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Limitation of Liability</h2>
            <p className="text-muted leading-relaxed">
              To the fullest extent permitted by law, Bluto and its creators shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the app. This includes but is not limited to damages arising from reliance on AI-generated content, service interruptions, or data loss.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Disclaimer of Warranties</h2>
            <p className="text-muted leading-relaxed">
              Bluto is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind, either express or implied. We do not guarantee that the service will be uninterrupted, error-free, or that AI responses will be accurate or suitable for any particular purpose.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">9. Account Termination</h2>
            <p className="text-muted leading-relaxed">
              We reserve the right to suspend or terminate your account if you violate these terms or engage in conduct that we determine to be harmful to other users or the service. You may delete your account at any time through the app settings.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">10. Indemnification</h2>
            <p className="text-muted leading-relaxed">
              You agree to indemnify, defend, and hold harmless Bluto, its creators, officers, directors, employees, and agents from and against any and all claims, liabilities, damages, losses, costs, and expenses (including reasonable attorney fees) arising out of or related to your use of the app, your violation of these terms, or your reliance on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">11. Governing Law</h2>
            <p className="text-muted leading-relaxed">
              These Terms shall be governed by and construed in accordance with applicable laws, without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">12. Changes to Terms</h2>
            <p className="text-muted leading-relaxed">
              We may update these Terms of Service from time to time. We will notify you of material changes by posting the updated terms within the app. Continued use of the app after changes are posted constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">13. Contact Us</h2>
            <p className="text-muted leading-relaxed">
              If you have any questions about these Terms of Service, please contact us at{" "}
              <a href="mailto:support@bluto.co" className="text-accent hover:text-accent-light transition-colors">
                support@bluto.co
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-card-border">
          <Link href="/" className="text-sm text-accent hover:text-accent-light transition-colors">
            &larr; Back to home
          </Link>
        </div>
      </article>
    </div>
  );
}
